services:
  mongo:
    image: mongo
    container_name: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nitin
      - MONGO_INITDB_ROOT_PASSWORD=nitin
    volumes:
      - mongo:/data
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=nitin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=nitin
      - ME_CONFIG_MONGODB_SERVER=mongo

volumes:
  mongo: {}
